config = {
    'language_code' : 'en-US',
    "voice": {
        "language_code": "en-US",
        "name": "en-US-Wavenet-J",   
    },
    "pitch_rates" :[-10., -8., -6., -4., -2., 0., 2., 4., 6., 8., 10.],
    "speed_rates": [0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0],
    "path" : "resources",
    "texts" : ["Let my words wash over you, and take the suggestions as you desire them.",
    "Everything here is safe, calm, and peaceful. Let yourself sink into the couch/chair as your relax deeply.",
    "Your eyes may feel heavy and want to close. Let your body sink naturally down as your muscles relax. Listen to your body and my voice as you begin to feel calm.",
    "You are in complete control of this time. You will only accept those suggestions which are for your benefit and that you are willing to accept.",
    "Breathe in deeply now, filling your chest and lungs",
    "Slowly let the air out of your chest, completely emptying your lungs.",
    "Choose an object, any object, and rest your eyes on it.",
    "I want you to pay attention to that object",
    "Try and focus on the object.",
    "Let your eyes and eyelids relax, growing heavy.",
    "Relax your toes and feet",
    "Relax your feet and ankles. Feel the muscles lighten and loosen in your feet, as if they require no effort to maintain.",
    "You can feel your eyelids getting heavy. Let them drift and fall.",
    "You are letting yourself slip deeper and deeper into a calm, peaceful trance.",
    "You can feel yourself relaxing now. You can feel a heavy, relaxed feeling coming over you. And as I continue to talk, that heavy relaxed feeling will get stronger and stronger, until it carries you into a deep, peaceful state of relaxation.",
    "Every word that I utter is putting you faster and deeper, and faster and deeper, into a calm, peaceful state of relaxation.",
    "Sinking down, and shutting down. Sinking down, and shutting down. Sinking down, and shutting down, shutting down completely.",
    "And the deeper you go, the deeper you are able to go. And the deeper you go, the deeper you want to go, and the more enjoyable the experience becomes.",
    "Imagine yourself at the top of a long staircase in a warm, quiet room",
    "Take the first step down and feel yourself sinking deeper into relaxation.",
    "Each step is a step further into your subconscious.",
    "You step down the second step and feel yourself getting calmer and calmer.",
    "When you reach the third step, your body feels as if it is floating blissfully away.",
    "Envision a door at the bottom as well, leading to a state of pure relaxation.",
    "I'm going to count from one to five, and at the count of five you will be feeling wide awake, fully alert, and completely refreshed.",
    "Five",
    "Four",
    "Three",
    "Two",
    "One"
    ]
}